---
- name: update apt caches
  apt:
    update_cache: 'yes'
    cache_valid_time: 3600

- name: install lvm2
  apt:
    name: lvm2

- name: create volume group
  lvg:
    vg: "{{ lvm_vg }}"
    pvs: "{{ ','.join(pvs) }}"

- name: create logical volume
  lvol:
    vg: "{{ lvm_vg }}"
    lv: "{{ lvm_lv_name }}"
    size: "{{ lvm_lv_size }}"

- name: create filesystem
  filesystem:
    fstype: "{{ lvm_lv_fstype }}"
    dev: "/dev/{{ lvm_vg }}/{{ lvm_lv_name }}"

- name: mount partition
  mount:
    name: "{{ lvm_lv_mount }}"
    src: "/dev/{{ lvm_vg }}/{{ lvm_lv_name }}"
    fstype: "{{ lvm_lv_fstype }}"
    state: mounted

- include: bindings.yml
  when: lvm_bindings
