---
- name: ensure volumes variable
  assert:
    that:
      - 'volumes'

- include: volumes.yml
  when: volumes == 'auto'

- name: set pvs for lvm
  set_fact:
    pvs: "{{ volumes }}"
  when: volumes != 'auto'

- include: lvm.yml
  when: pvs
