---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: xenial-lvm
    box: ubuntu/xenial64
    raw_config_args:
      - "customize ['createmedium', '--filename', 'xenial64-vol1.vdi', '--size', 128, '--format', 'VDI']"
      - "customize ['createmedium', '--filename', 'xenial64-vol2.vdi', '--size', 128, '--format', 'VDI']"
      - "customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'xenial64-vol1.vdi']"
      - "customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', 'xenial64-vol2.vdi']"
  - name: trusty-lvm
    box: ubuntu/trusty64
    raw_config_args:
      - "customize ['createmedium', '--filename', 'trusty64-vol1.vdi', '--size', 128, '--format', 'VDI']"
      - "customize ['createmedium', '--filename', 'trusty64-vol2.vdi', '--size', 128, '--format', 'VDI']"
      - "customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'trusty64-vol1.vdi']"
      - "customize ['storageattach', :id, '--storagectl', 'SATAController', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', 'trusty64-vol2.vdi']"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
